# Base image
FROM python:3.12.6

# Certificates 
ENV CURL_CA_BUNDLE=''

# Project label
LABEL project="rmr-agent-frontend"

# Set the working directory
WORKDIR /rmr_agent

# Copy and install dependencies
COPY requirements.txt ./
RUN pip install --upgrade pip --index-url https://artifactory.paypalcorp.com/artifactory/api/pypi/paypal-python-all/simple  \
    && pip install -r requirements.txt --index-url https://artifactory.paypalcorp.com/artifactory/api/pypi/paypal-python-all/simple

# Copy the entire project (or just frontend if you refactor)
COPY . .

# Set PYTHONPATH to include /app
ENV PYTHONPATH=/rmr_agent

# Expose Streamlit's default port
EXPOSE 8501

# Run Streamlit
CMD ["streamlit", "run", "rmr_agent/frontend/ui.py", "--server.port=8501", "--server.address=0.0.0.0"]