nodes:
- Driver Creation:
    file_name: repos/ql-store-recommendation-prod/research/pipeline/00_driver.ipynb
    line_range: Lines 4-512
    inputs:
      file_path: ../config/base_config.yaml
      bq_prefix: "config['general_config']['bq_project_dataset_prefix']"
      training_exclude_merch: "config['driver_config']['training_exclude_merch']"
      train_start_date: "config['driver_config']['train_start_date']"
      oot_start_date: "config['driver_config']['oot_start_date']"
      val_start_date: "config['driver_config']['val_start_date']"
      training_hot_positive_attributed_txn_sampling_alpha: "config['driver_config']['training_hot_positive_attributed_txn_sampling_alpha']"
      training_attributed_txn_upsampling_rate: "config['driver_config']['training_attributed_txn_upsampling_rate']"
      removing_highly_active_user_threshold: "config['driver_config']['removing_highly_active_user_threshold']"
      removing_highly_active_user_merchant_threshold: "config['driver_config']['removing_highly_active_user_merchant_threshold']"
      removing_highly_active_user_merchant_date_threshold: "config['driver_config']['removing_highly_active_user_merchant_date_threshold']"
      training_hot_positive_organic_txn_sampling_alpha: "config['driver_config']['training_hot_positive_organic_txn_sampling_alpha']"
      save_label_mixing_rate: "config['driver_config']['save_label_mixing_rate']"
      ratio_for_hard_negtive: "config['driver_config']['ratio_for_hard_negtive']"
      hard_negative_impression_time_window: "config['driver_config']['hard_negative_impression_time_window']"
      negative_sampling_avoid_delay_postive_feedback_window: "config['driver_config']['negative_sampling_avoid_delay_postive_feedback_window']"
      training_hot_negative_sampling_alpha: "config['driver_config']['training_hot_negative_sampling_alpha']"
      uniform_negative_postive_ratio: "config['driver_config']['uniform_negative_postive_ratio']"
    outputs:
      driver_oot: "{bq_prefix}driver_oot"
      driver_simu: "{bq_prefix}driver_simu"
      driver_simu_consumer: "{bq_prefix}driver_simu_consumer"
- Feature Engineering:
    file_name: repos/ql-store-recommendation-prod/research/pipeline/01_bq_feat.ipynb
    line_range: Lines 17-817
    inputs:
      file_path: ../config/base_config.yaml
      bq_prefix: "config['general_config']['bq_project_dataset_prefix']"
      train_start_date: "config['driver_config']['train_start_date']"
    outputs:
      driver_consumer_base_gender_table: "{bq_prefix}driver_consumer_base_gender"
- Data Pulling:
    file_name: repos/ql-store-recommendation-prod/research/pipeline/01_varmart_feat.ipynb
    line_range: Lines 23-67
    inputs:
      stage: training
      seq_num: '20231005'
      is_prod: 'True'
      job_name: ql_store_rmr
      group_name: mls_gads
      model_name: ql_store_rmr_datafetcher
      model_owner: chenzhao
      description: ranking_combined_datafetcher
      manager: Farhad
      on_gcp: 'True'
      gcp_project_id: ccg24-hrzana-gds-pacman
      gcs_bucket_name: pypl-bkt-rsh-row-std-gds-pacman
      bq_materialization_project: pypl-bods
      bq_materialization_dataset: rsh_row_gds_pacman
      driver_loc: gs://pypl-bkt-rsh-row-std-gds-pacman/user/chenzhao/prod/ql-store-rmr/data/ql_store_rmr_driver_simu_consumer
      variables: "[\"prmry_addr_state\", \"days_on_file\", \"ebay_member_y_n\", \"\
        consu_engagmnt_seg_key\", \"prmry_cc_type_code\", \"days_appweb_visit\", \"\
        consu_age_band_key\", \"consu_income_band_key\", \"consu_dmgrphc_seg_key\"\
        ]"
      split_ratio: "{\"train\": 1.0}"
      num_of_splits: '1'
    outputs:
      data_loc: gs://pypl-bkt-rsh-row-std-gds-pacman/user/chenzhao/prod/ql-store-rmr/data/ql_store_rmr_driver_simu_consumer_varmart
- Feature Consolidation:
    file_name: repos/ql-store-recommendation-prod/research/pipeline/02_combine.ipynb
    line_range: Lines 17-624
    inputs:
      file_path: ../config/base_config.yaml
      bq_prefix: "config['general_config']['bq_project_dataset_prefix']"
    outputs:
      driver_dev_features_table: "{bq_prefix}driver_dev_features"
      driver_oot_features_table: "{bq_prefix}driver_oot_features"
      driver_oot_features_expand_seq_table: "{bq_prefix}driver_oot_features_expand_seq"
      export_uri: gs://pypl-bkt-rsh-row-std-gds-pacman/user/chenzhao/prod/ql-store-rmr/data/ql_store_rmr_driver_dev_features/part*.parquet
- Data Preprocessing:
    file_name: repos/ql-store-recommendation-prod/research/pipeline/03_prepare_training_data.ipynb
    line_range: Lines 21-175
    inputs:
      model_version_base: ../artifacts/din_<today_date>
      directory: ../data/ql_store_rmr_driver_dev_features
      parquet_files: "[\"file1.parquet\", \"file2.parquet\", ...]"
      state_to_abbreviation: "{\"ALABAMA\": \"AL\", \"ALASKA\": \"AK\", ...}"
      categorical_features: "[\"sndr_consu_engagmnt_seg_key\", \"sndr_ebay_member_y_n\"\
        , \"gender\", ...]"
      numeric_features: "[\"sndr_rcvr_txn_num_30d\", \"sndr_rcvr_txn_num_180d\", ...]"
      rcvr_id_tokenizer_params: "{\"num_words\": 1000, \"oov_token\": \"<OOV>\"}"
      chunk_size: '1000000'
    outputs:
      model_version: din_<today_date>
      exported_feature_transformer: ../artifacts/din_<today_date>/exported_feature_transformer
      output_dir: ../data/ql_store_rmr_driver_dev_features_transformed
      rcvr_id_tokenizer_path: ../artifacts/din_<today_date>/exported_feature_transformer/rcvr_id_tokenizer
      categorical_feature_encoders_path: ../artifacts/din_<today_date>/exported_feature_transformer/categorical_feature_encoders
      numerical_feature_scalars_path: ../artifacts/din_<today_date>/exported_feature_transformer/numerical_feature_scalars
- Model Training:
    file_name: repos/ql-store-recommendation-prod/research/pipeline/04_training.ipynb
    line_range: Lines 140-170
    inputs:
      train_data_path: ../data/ql_store_rmr_driver_dev_features_transformed
      numeric_names: "[\"sndr_rcvr_txn_num_30d\", \"sndr_rcvr_txn_num_180d\", \"sndr_rcvr_txn_num_365d\"\
        , ...]"
      rcvr_id_names: "[\"rcvr_id\"]"
      gpt_cate_names: "[\"gpt_1st_category_l2_index\", \"sndr_1st_freq_merchant_category_30d\"\
        , ...]"
      batch_size: "config['training_config']['DIN']['batch_size']"
      learning_rate: "config['training_config']['DIN']['learning_rate']"
      dnn_use_bn: "config['training_config']['DIN']['dnn_use_bn']"
      dnn_hidden_units: "config['training_config']['DIN']['dnn_hidden_units']"
      dnn_activation: "config['training_config']['DIN']['dnn_activation']"
      att_hidden_size: "config['training_config']['DIN']['att_hidden_size']"
      att_activation: "config['training_config']['DIN']['att_activation']"
      att_weight_normalization: "config['training_config']['DIN']['att_weight_normalization']"
      l2_reg_dnn: "config['training_config']['DIN']['l2_reg_dnn']"
      l2_reg_embedding: "config['training_config']['DIN']['l2_reg_embedding']"
      dnn_dropout: "config['training_config']['DIN']['dnn_dropout']"
      seed: "config['training_config']['DIN']['seed']"
      epochs: "config['training_config']['DIN']['epochs']"
    outputs:
      model_artifact_path: "os.path.join(exported_model_base, 'din.h5')"
      tf_model_path: "os.path.join(exported_model_base, 'din_saved_model')"
- Model Packaging:
    file_name: repos/ql-store-recommendation-prod/research/pipeline/04_training.ipynb
    line_range: Lines 171-185
    inputs:
      trained_model_path: "os.path.join(exported_model_base, 'din_saved_model')"
    outputs:
      onnx_model_path: "os.path.join(exported_model_base, 'din.onnx')"
      oot_scoring_path: "os.path.join(exported_model_base, 'oot_scoring')"
      prod_model_path: "os.path.join(exported_model_base, 'din_prod.m')"
- Model Scoring:
    file_name: repos/ql-store-recommendation-prod/research/pipeline/05_scoring_oot.ipynb
    line_range: Lines 25-94
    inputs:
      working_path: /projects/gds-packman/apps/ql-store-recommendation-prod/research
      params_path: /projects/gds-packman/apps/ql-store-recommendation-prod/research/config
      section_name: oot_data_scoring
      model_version_path: /projects/gds-packman/apps/ql-store-recommendation-prod/research/_current_model_version
      exported_model_base: "/projects/gds-packman/apps/ql-store-recommendation-prod/research/artifacts/{model_version}/exported_models"
      m_local_folder: /projects/gds-packman/apps/ql-store-recommendation-prod/research/artifacts/din_20240708/18/exported_models/oot_scoring
      m_gcp_folder: gs://pypl-bkt-rsh-row-std-gds-pacman/user/chenzhao/prod/ql-store-rmr/challenger/oot_scoring
      oot_data_path: gs://pypl-bkt-rsh-row-std-gds-pacman/user/chenzhao/prod/ql-store-rmr/data/ql_store_rmr_oot_transformed
      eval_path: gs://pypl-bkt-rsh-row-std-gds-pacman/user/chenzhao/prod/ql-store-rmr/data/ql_store_rmr_oot_transformed_scored
    outputs:
      eval_result_path: gs://pypl-bkt-rsh-row-std-gds-pacman/user/chenzhao/prod/ql-store-rmr/data/ql_store_rmr_oot_transformed_scored
      log_file: "/projects/gds-packman/apps/ql-store-recommendation-prod/research/logs/{job_id}.log"
- Model Evaluation:
    file_name: repos/ql-store-recommendation-prod/research/pipeline/06_evaluation.ipynb
    line_range: Lines 375-731
    inputs:
      model_version_path: ../_current_model_version
      model_version_base: "../artifacts/{model_version}/18"
      config_file_path: ../config/base_config.yaml
      bq_project_dataset_prefix: "{config['general_config']['bq_project_dataset_prefix']}"
      oot_start_date: "{config['driver_config']['oot_start_date']}"
      remove_list: "'1365556366671835703','2254348706417584521','1581565211190403045','1157330454984142772','1339933886421356550','1812170125034785903','6053464759929799123','1587111025150613712','1672368731209095395','1365556366671835703','6085552794250364378','1954349237309389875'"
    outputs:
      exported_eval_readout_base: "../artifacts/{model_version}/18/exported_eval_readouts"
      performance_all_csv: "../artifacts/{model_version}/18/exported_eval_readouts/performane_all.csv"
      performance_all_png: "../artifacts/{model_version}/18/exported_eval_readouts/performane_all.png"
      performance_ftu_csv: "../artifacts/{model_version}/18/exported_eval_readouts/performane_ftu.csv"
      performance_ftu_png: "../artifacts/{model_version}/18/exported_eval_readouts/performane_ftu.png"
      performance_wo_ebay_csv: "../artifacts/{model_version}/18/exported_eval_readouts/performane_wo_ebay.csv"
      performance_wo_ebay_png: "../artifacts/{model_version}/18/exported_eval_readouts/performane_wo_ebay.png"
edges:
- from: driver_creation
    to: data_pulling
    attributes:
      driver_loc: "gs://pypl-bkt-rsh-row-std-gds-pacman/user/chenzhao/prod/ql-store-rmr/data/ql_store_rmr_driver_simu_consumer"
  - from: feature_engineering
    to: data_pulling
    attributes:
      driver_simu_consumer: "{bq_prefix}driver_simu_consumer"
  - from: feature_consolidation
    to: data_preprocessing
    attributes:
      export_uri: "gs://pypl-bkt-rsh-row-std-gds-pacman/user/chenzhao/prod/ql-store-rmr/data/ql_store_rmr_driver_dev_features/part*.parquet"
  - from: data_preprocessing
    to: model_training
    attributes:
      output_dir: "../data/ql_store_rmr_driver_dev_features_transformed"
  - from: model_training
    to: model_packaging
    attributes:
      tf_model_path: "os.path.join(exported_model_base, 'din_saved_model')"
  - from: model_packaging
    to: model_scoring
    attributes:
      oot_scoring_path: "os.path.join(exported_model_base, 'oot_scoring')"
  - from: model_scoring
    to: model_evaluation
    attributes:
      eval_result_path: "gs://pypl-bkt-rsh-row-std-gds-pacman/user/chenzhao/prod/ql-store-rmr/data/ql_store_rmr_oot_transformed_scored"