nodes:
- Driver Creation:
    file_name: rmr_agent/repos/ql-store-recommendation-prod/research/pipeline/00_driver.py
    line_range: Lines 1-513
    inputs:
      file_path: "../config/base_config.yaml"
      bq_project_dataset_prefix: "pyplods.gds_pacman_prod."
      training_exclude_merch: "{config['driver_config']['training_exclude_merch']}"
      train_start_date: "current_date0"
      oot_start_date: "current_date0"
      training_hot_positive_attributed_txn_sampling_alpha: "0.9999"
      training_attributed_txn_upsampling_rate: "10"
      removing_highly_active_user_threshold: "99999"
      removing_highly_active_user_merchant_threshold: "99999"
      removing_highly_active_user_merchant_date_threshold: "99999"
      training_hot_positive_organic_txn_sampling_alpha: "0.9999"
      val_start_date: "current_date0"
      save_label_mixing_rate: "0.00000000001"
      ratio_for_hard_negtive: "0"
      hard_negative_impression_time_window: "30"
      negative_sampling_avoid_delay_postive_feedback_window: "30"
      training_hot_negative_sampling_alpha: "0"
      uniform_negative_postive_ratio: "2"
    outputs:
      driver_dev: "pyplods.gds_pacman_prod.driver_dev"
      driver_oot: "pyplods.gds_pacman_prod.driver_oot"
      driver_simu: "pyplods.gds_pacman_prod.driver_simu"
      driver_simu_consumer: "pyplods.gds_pacman_prod.driver_simu_consumer"
- Feature Engineering:
    file_name: rmr_agent/repos/ql-store-recommendation-prod/research/pipeline/01_bq_feat.py
    line_range: 1-819
    inputs:
      file_path: ../config/base_config.yaml
      bq_prefix: "pyplods.gds_pacman_prod."
      train_start_date: "current_date0"
    outputs:
      final_table: "pyplods.gds_pacman_prod.driver_consumer_base_gender"
- Data Pulling:
    file_name: rmr_agent/repos/ql-store-recommendation-prod/research/pipeline/01_varmart_feat.py
    line_range: 1-73
    inputs:
      gcp_project_id: ccg24-hrzana-gds-pacman
      gcs_bucket_name: pypl-bkt-rsh-row-std-gds-pacman
      bq_materialization_project: pypl-bods
      bq_materialization_dataset: rsh_row_gds_pacman
      driver_loc: gs://pypl-bkt-rsh-row-std-gds-pacman/user/chenzhao/prod/ql-store-rmr/data/ql_store_rmr_driver_simu_consumer
      variables: "['prmry_addr_state', 'days_on_file', 'ebay_member_y_n', 'consu_engagmnt_seg_key',\
        \ 'prmry_cc_type_code', 'days_appweb_visit', 'consu_age_band_key', 'consu_income_band_key',\
        \ 'consu_dmgrphc_seg_key']"
      split_ratio: "{\"train\": 1.0}"
      num_of_splits: '1'
    outputs:
      data_loc: gs://pypl-bkt-rsh-row-std-gds-pacman/user/chenzhao/prod/ql-store-rmr/data/ql_store_rmr_driver_simu_consumer_varmart
- Feature Consolidation:
    file_name: rmr_agent/repos/ql-store-recommendation-prod/research/pipeline/02_combine.py
    line_range: 1-642
    inputs:
      file_path: ../config/base_config.yaml
      bq_prefix: "pyplods.gds_pacman_prod."
      driver_consumer_base_gender: "pyplods.gds_pacman_prod.driver_consumer_base_gender"
      ql_store_honey_merch_quality_scores_external: pypl-bods.gds_pacman_prod.ql_store_honey_merch_quality_scores_external
      driver_simu_consumer_varmart_external: "pypl-bods.gds_pacman_prod.driver_simu_consumer_varmart_external"
      store_recommendation_kg_embedding_32_v2: pypl-bods.gds_pacman_prod.store_recommendation_kg_embedding_32_v2
    outputs:
      gs: '//pypl-bkt-rsh-row-std-gds-pacman/user/chenzhao/prod/ql-store-rmr/data/ql_store_rmr_driver_dev_features/part*.parquet:'
- Data Preprocessing:
    file_name: rmr_agent/repos/ql-store-recommendation-prod/research/pipeline/03_prepare_training_data.py
    line_range: 1-185
    inputs:
      model_version_base: ../artifacts/din_<today_date>
      exported_feature_transformer: ../artifacts/din_<today_date>/exported_feature_transformer
      directory: ../data/ql_store_rmr_driver_dev_features
      parquet_files: List of parquet files in the directory
      state_to_abbreviation: Dictionary mapping state names to abbreviations
      categorical_features: "['sndr_consu_engagmnt_seg_key', 'sndr_ebay_member_y_n',\
        \ 'gender', 'sndr_prmry_cc_type_code', 'sndr_consu_age_band_key', 'sndr_consu_dmgrphc_seg_key']"
      numeric_features: "['sndr_rcvr_txn_num_30d', 'sndr_rcvr_txn_num_180d', 'sndr_rcvr_txn_num_365d',\
        \ 'sndr_rcvr_txn_amt_30d', 'sndr_rcvr_txn_amt_180d', ... (abbreviated)]"
      rcvr_id_tokenizer_params: "{'num_words': 1000, 'oov_token': '<OOV>'}"
      output_dir: ../data/ql_store_rmr_driver_dev_features_transformed
      chunk_size: '1000000'
    outputs:
      transformed_data_path: ../data/ql_store_rmr_driver_dev_features_transformed
      rcvr_id_tokenizer_path: ../artifacts/din_<today_date>/exported_feature_transformer/rcvr_id_tokenizer
      categorical_feature_encoders_path: ../artifacts/din_<today_date>/exported_feature_transformer/categorical_feature_encoders
      numerical_feature_scalars_path: ../artifacts/din_<today_date>/exported_feature_transformer/numerical_feature_scalars
- Model Training:
    file_name: rmr_agent/repos/ql-store-recommendation-prod/research/pipeline/04_training.py
    line_range: 1-170
    inputs:
      file_path: ../config/base_config.yaml
      model_version_base: "../artifacts/{model_version}/19"
      exported_feature_transformer: "../artifacts/{model_version}/exported_feature_transformer"
      directory: ../data/ql_store_rmr_driver_dev_features_transformed
      numeric_names: "[\"sndr_rcvr_txn_num_30d\", \"sndr_rcvr_txn_num_180d\", \"sndr_rcvr_txn_num_365d\"\
        , ...]"
      rcvr_id_names: "['rcvr_id']"
      gpt_cate_names: "['gpt_1st_category_l2_index', 'sndr_1st_freq_merchant_category_30d',\
        \ ...]"
      batch_size: 256
      learning_rate: 0.0001
      dnn_use_bn: True
      dnn_hidden_units: [100,40]
      dnn_activation: "relu"
      att_hidden_size: [60,30]
      att_activation: "dice"
      att_weight_normalization: False
      l2_reg_dnn: 0.001
      l2_reg_embedding: 0.002
      dnn_dropout: 0.28
      seed: 1024
      epochs: 50
    outputs:
      h5_model_path: "../artifacts/{model_version}/19/exported_models/din.h5"
      tf_model_path: "../artifacts/{model_version}/19/exported_models/din_saved_model"
- Model Packaging:
    file_name: rmr_agent/repos/ql-store-recommendation-prod/research/pipeline/04_training.py
    line_range: 171-269
    inputs:
      model: '`model` (TensorFlow model object)'
      exported_model_base: "`os.path.join(model_version_base, 'exported_models')`"
      input_mappings: "'hist_gpt_1st_category_l2_index': `[f'hist_gpt_1st_category_{i}'\
        \ for i in range(1, 101)]`"
      output_mappings: "`{model.output.name[:-2]: 'out'}`"
      categorical_feature_encoders: "`os.path.join(exported_feature_transformer, 'categorical_feature_encoders')`"
      numerical_feature_scalars: "`os.path.join(exported_feature_transformer, 'numerical_feature_scalars')`"
      test_cust: '`test_cust` (variable not defined in the provided code)'
      test_date: '`test_date` (variable not defined in the provided code)'
      test_df: "`data[(data['cust_id'] == test_cust) & (data['run_date'] == test_date)]`"
      test_data_local: '`test_data_local` (dictionary created from `test_df`)'
      test_data_tf: '`test_data_tf` (dictionary created from `test_df`)'
      onnx_output_path: "`os.path.join(exported_model_base, 'din.onnx')`"
      saved_model_path: "`os.path.join(exported_model_base, 'din_saved_model')`"
      output_file: '`./testdata/testdata.json`'
    outputs:
      h5_model_path: "`os.path.join(exported_model_base, 'din.h5')`"
      tf_model_path: "`os.path.join(exported_model_base, 'din_saved_model')`"
      onnx_spec: '`onnx_spec.save(exported_model_base)`'
      prod_model: '`prod_model.save(exported_model_base)`'
      path: '`exported_model_base + ''/din_prod.m''`'
      test_data: "`{\"data\": {\"names\": inputs, \"ndarray\": [test_data_local[feat][0]\
        \ for feat in inputs]}}`"
      onnx_output_path: "`os.path.join(exported_model_base, 'din.onnx')`"
      results_ort: "`sess.run(None, test_data_onnx)`"
- Model Scoring:
    file_name: rmr_agent/repos/ql-store-recommendation-prod/research/pipeline/05_scoring_oot.py
    line_range: 1-104
    inputs:
      working_path: /projects/gds-packman/apps/ql-store-recommendation-prod/research
      params_path: /projects/gds-packman/apps/ql-store-recommendation-prod/research/config
      section_name: oot_data_scoring
      model_version_path: /projects/gds-packman/apps/ql-store-recommendation-prod/research/_current_model_version
      exported_model_base: "/projects/gds-packman/apps/ql-store-recommendation-prod/research/artifacts/{model_version}/exported_models"
      m_local_folder: /projects/gds-packman/apps/ql-store-recommendation-prod/research/artifacts/din_20240708/18/exported_models/oot_scoring
      m_gcp_folder: gs://pypl-bkt-rsh-row-std-gds-pacman/user/chenzhao/prod/ql-store-rmr/challenger/oot_scoring
      oot_data_path: gs://pypl-bkt-rsh-row-std-gds-pacman/user/chenzhao/prod/ql-store-rmr/data/ql_store_rmr_oot_transformed
      eval_path: gs://pypl-bkt-rsh-row-std-gds-pacman/user/chenzhao/prod/ql-store-rmr/data/ql_store_rmr_oot_transformed_scored
    outputs:
      eval_result_path: gs://pypl-bkt-rsh-row-std-gds-pacman/user/chenzhao/prod/ql-store-rmr/data/ql_store_rmr_oot_transformed_scored
      log_file: "/projects/gds-packman/apps/ql-store-recommendation-prod/research/logs/{job_id}.log"

edges:
- from: Driver Creation
  to: Data Pulling
  attributes:
    driver_simu_consumer: "gs://pypl-bkt-rsh-row-std-gds-pacman/user/chenzhao/prod/ql-store-rmr/data/ql_store_rmr_driver_simu_consumer"
- from: Driver Creation
  to: Feature Consolidation
  attributes:
    driver_dev: "pyplods.gds_pacman_prod.driver_dev"
- from: Feature Engineering
  to: Feature Consolidation
  attributes:
    final_table: "pyplods.gds_pacman_prod.driver_consumer_base_gender"
- from: Data Pulling
  to: Feature Consolidation
  attributes:
    data_loc: "gs://pypl-bkt-rsh-row-std-gds-pacman/user/chenzhao/prod/ql-store-rmr/data/ql_store_rmr_driver_simu_consumer_varmart"
- from: Feature Consolidation
  to: Data Preprocessing
  attributes:
    gs: "gs://pypl-bkt-rsh-row-std-gds-pacman/user/chenzhao/prod/ql-store-rmr/data/ql_store_rmr_driver_dev_features/part*.parquet"
- from: Data Preprocessing
  to: Model Training
  attributes:
    transformed_data_path: "../data/ql_store_rmr_driver_dev_features_transformed"
- from: Model Training
  to: Model Packaging
  attributes:
    h5_model_path: "../artifacts/{model_version}/19/exported_models/din.h5"
    tf_model_path: "../artifacts/{model_version}/19/exported_models/din_saved_model"
- from: Model Packaging
  to: Model Scoring
  attributes:
    tf_model_path: "/projects/gds-packman/apps/ql-store-recommendation-prod/research/artifacts/{model_version}/exported_models/din_saved_model"